FROM node:lts-slim

# Set environment variables
ENV NODE_ENV="development"
ENV SERVER_PORT="8080"
ENV POSTGRES_URI="postgresql://postgres_user:postgres_password@pg_dev:5432/postgres_db"
ENV SECRET_COOKIE="cookie_secret"
ENV REDIS_HOST="redis_dev"
ENV REDIS_PORT="6379"

# Install openssl and curl (needed for prisma migrate)
RUN apt update && apt install -y openssl && apt install -y curl

WORKDIR /app
COPY . .

CMD ["npm", "run", "dev"]

# WARNINGS: 
# - Do not use prisma generate or migrate functions in dockerfile as it will not work during build time
# - Do not copy your node_modules folder in production
# - Do not expose your db port in production
# - Do use docker-compose for production!